-- PRODUCER
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (1, 'PRODUCER', 'SKATTEETATEN', 'Skatteetaten', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (2, 'PRODUCER', 'BRUKER', 'Informasjon oppgitt av bruker', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (3, 'PRODUCER', 'UTLENDINGSDIREKTORATET', 'Utlendingsdirektoratet', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (4, 'PRODUCER', 'UTENLANDS_TRYGDEMYNDIGHET', 'Utenlands trygdemyndighet', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (5, 'PRODUCER', 'ARBEIDSGIVER', 'Arbeidsgiver', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (6, 'PRODUCER', 'REVISOR', 'Revisor', 'Flyway', now());

-- CATEGORY
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (7, 'CATEGORY', 'PERSONALIA', 'Personalia', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (8, 'CATEGORY', 'KONTAKTOPPLYSNINGER', 'Adresse og kontaktopplysninger', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (9, 'CATEGORY', 'FAMILIERELASJONER', 'Familierelasjoner', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (10, 'CATEGORY', 'FULLMEKTIG', 'Verge og fullmektig', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (11, 'CATEGORY', 'FOLKETRYGD', 'Opphold og medlemskap i folketrygden', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (12, 'CATEGORY', 'ARBEIDSFORHOLD', 'Arbeidsforhold', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (13, 'CATEGORY', 'UTDANNING', 'Utdanning', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (14, 'CATEGORY', 'CV', 'CV', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (15, 'CATEGORY', 'SKOLE_BARNEHAGE', 'Opplysninger om skole og barnehageplass', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (16, 'CATEGORY', 'INNTEKT_YTELSER', 'Inntekt, trygde- og pensjonsytelser', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (17, 'CATEGORY', 'SKATTEOPPLYSNINGER', 'Skatteopplysninger', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (18, 'CATEGORY', 'OKONOMISKE_OPPLYSNINGER', 'Andre økonomiske opplysninger', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (19, 'CATEGORY', 'HELSEOPPLYSNNGER', 'Helseopplysninger', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (20, 'CATEGORY', 'INSTITUSJONSOPPHOLD', 'Institusjonsopphold', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (21, 'CATEGORY', 'LOVOVERTREDELSER', 'Straffedommer og lovovertredelser', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (22, 'CATEGORY', 'BIOMETRISKE_KJENNETEGN', 'Biometriske kjennetegn som kan identifisere enkeltperson', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (23, 'CATEGORY', 'MEDIER_KJENNETEGN', 'Personportrett, video- og lydopptak som kan identifisere enkeltperson', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (24, 'CATEGORY', 'MOTORVOGNOPPLYSNINGER', 'Motorvognopplysninger', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (25, 'CATEGORY', 'TRO_ETNISITET', 'Opplysninger om trossamfunn og etnisitet', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (26, 'CATEGORY', 'VERNEPLIKT', 'Opplysninger om verneplikt', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (27, 'CATEGORY', 'REISEVEI', 'Opplysninger om reisevei', 'Flyway', now());

-- SYSTEM
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (28, 'SYSTEM', 'TPS', 'Tjenestebasert PersondataSystem', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (29, 'SYSTEM', 'INST', 'Institusjonsopphold', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (30, 'SYSTEM', 'POPP', 'Pensjonfaglig opptjeningsregiste', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (31, 'SYSTEM', 'TP', 'Tjenestepensjon', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (32, 'SYSTEM', 'AA_REG', 'Arbeidsgiver / Arbeidstaker register', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (33, 'SYSTEM', 'OPPDRAG', 'Oppdragssystemet', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (34, 'SYSTEM', 'PESYS', 'Pensjonssystem', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (35, 'SYSTEM', 'ARENA', 'Arbeidsrelatert saksbehandlingsystem', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (36, 'SYSTEM', 'INFOTRYGD', 'System for saksbehandling av ytelser og trygd', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (37, 'SYSTEM', 'BISYS', 'Bidragsløsningen', 'Flyway', now());

