-- PRODUCER
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'PRODUCER', 'SKATTEETATEN', 'Skatteetaten', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'PRODUCER', 'BRUKER', 'Informasjon oppgitt av bruker', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'PRODUCER', 'UTLENDINGSDIREKTORATET', 'Utlendingsdirektoratet', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'PRODUCER', 'UTENLANDS_TRYGDEMYNDIGHET', 'Utenlands trygdemyndighet', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'PRODUCER', 'ARBEIDSGIVER', 'Arbeidsgiver', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'PRODUCER', 'REVISOR', 'Revisor', 'Flyway', now());

-- CATEGORY
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'PERSONALIA', 'Personalia', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'KONTAKTOPPLYSNINGER', 'Adresse og kontaktopplysninger', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'FAMILIERELASJONER', 'Familierelasjoner', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'FULLMEKTIG', 'Verge og fullmektig', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'FOLKETRYGD', 'Opphold og medlemskap i folketrygden', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'ARBEIDSFORHOLD', 'Arbeidsforhold', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'UTDANNING', 'Utdanning', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'CV', 'CV', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'SKOLE_BARNEHAGE', 'Opplysninger om skole og barnehageplass', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'INNTEKT_YTELSER', 'Inntekt, trygde- og pensjonsytelser', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'SKATTEOPPLYSNINGER', 'Skatteopplysninger', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'OKONOMISKE_OPPLYSNINGER', 'Andre økonomiske opplysninger', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'HELSEOPPLYSNNGER', 'Helseopplysninger', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'INSTITUSJONSOPPHOLD', 'Institusjonsopphold', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'LOVOVERTREDELSER', 'Straffedommer og lovovertredelser', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'BIOMETRISKE_KJENNETEGN', 'Biometriske kjennetegn som kan identifisere enkeltperson', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'MEDIER_KJENNETEGN', 'Personportrett, video- og lydopptak som kan identifisere enkeltperson', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'MOTORVOGNOPPLYSNINGER', 'Motorvognopplysninger', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'TRO_ETNISITET', 'Opplysninger om trossamfunn og etnisitet', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'VERNEPLIKT', 'Opplysninger om verneplikt', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'CATEGORY', 'REISEVEI', 'Opplysninger om reisevei', 'Flyway', now());

-- SYSTEM
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'SYSTEM', 'TPS', 'Tjenestebasert PersondataSystem', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'SYSTEM', 'INST', 'Institusjonsopphold', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'SYSTEM', 'POPP', 'Pensjonfaglig opptjeningsregiste', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'SYSTEM', 'TP', 'Tjenestepensjon', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'SYSTEM', 'AA_REG', 'Arbeidsgiver / Arbeidstaker register', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'SYSTEM', 'OPPDRAG', 'Oppdragssystemet', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'SYSTEM', 'PESYS', 'Pensjonssystem', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'SYSTEM', 'ARENA', 'Arbeidsrelatert saksbehandlingsystem', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'SYSTEM', 'INFOTRYGD', 'System for saksbehandling av ytelser og trygd', 'Flyway', now());
INSERT INTO BACKEND_SCHEMA.CODELIST(CODELIST_ID, LIST_NAME, CODE, DESCRIPTION, CREATED_BY, CREATED_DATE)
VALUES (NEXTVAL('BACKEND_SCHEMA.SEQ_CODELIST'), 'SYSTEM', 'BISYS', 'Bidragsløsningen', 'Flyway', now());

